### ISSUE TITLE
Spinning wheel "sending" on new fund creation

### ISSUE THREAD

**Issue by travs** [melonproject/portal#256]
When I run portal locally with a new metamask account, I am asked to create a new fund.
I enter the fund's name, click the button, confirm the tx in metamask, and the wheel just keeps spinning saying "sending", for about 10 minutes now.

In the dev console I'm getting this error:
```
modules.js?hash=87964fa…:21315 Uncaught ReferenceError: Buffer is not defined
    at Object.hexOrBuffer (http://localhost:3000/packages/modules.js?hash=87964fa31a493716426529ce55ab9dbb1434cf59:21315:8)
    at Object.decodeEvent (http://localhost:3000/packages/modules.js?hash=87964fa31a493716426529ce55ab9dbb1434cf59:21256:53)
    at http://localhost:3000/packages/modules.js?hash=87964fa31a493716426529ce55ab9dbb1434cf59:8873:38
    at Array.map (native)
    at Object.decodeLogs (http://localhost:3000/packages/modules.js?hash=87964fa31a493716426529ce55ab9dbb1434cf59:8844:19)
    at Object.callback (http://localhost:3000/packages/modules.js?hash=87964fa31a493716426529ce55ab9dbb1434cf59:8972:35)
    at http://localhost:3000/packages/modules.js?hash=87964fa31a493716426529ce55ab9dbb1434cf59:11904:25
    at http://localhost:3000/packages/modules.js?hash=87964fa31a493716426529ce55ab9dbb1434cf59:9889:9
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:168:7
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:7838:5
```

It looks like the tx [went through though](https://kovan.etherscan.io/tx/0x536767a2e009f1d57ee6de14d74c4491f53a2ef0456fa2edc4f4d4e704692ad7), and the fund shows up in the list, but the wheel keeps on spinning.

```
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial

node: 6.10.3
```

**Comment by travs** [comment]
Upgraded to node `v8.1.2` and the problem disappeared.
If the node version was the problem, a fix would be to add the [`engines`](https://stackoverflow.com/questions/28409883/how-to-enforce-a-specific-node-js-version-to-use) key to the package.json and specify a minimum version.

Since we're the only ones deploying the portal at the moment, it's not really an issue, so I'll close.
